[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aoc"
version = "0.0.1"
authors = [{name="Aaradhya Vaze"}, {name="Chaitanya Chawak"}]
readme = "README.md"
requires-python = ">=3.7"
